### ISSUE TITLE
Adding missing options to the Group Actor

### ISSUE THREAD

**Issue by MadLetter** [fvtt-fria-ligan/twilight2000-foundry-vtt#102]
### Is your feature request related to a problem? Please describe.
Not related to a problem.

### Who would use it?
Anyone using the Group Sheet for tracking and utilizing the relevant tasks, either the group as such or players dedicated to making said rolls.

### What part of the system?
Sheets

### How would it work?
Several actions are missing from the Group Sheet that are not centralized in the part of the book. Gathering is missing, and so is vehicle servicing and gun servicing, as well as Gear Repair in general. There may be others scattered throughout the book I haven't found yet, but those are the chief ones that come to mind.

### Why should this be added?
I intend to heavily use the Group Sheet to track characters' shifts, and I think many others would do the same. Adding missing actions to "automate and track" would be a great help.

### Additional context
No added context.

**Comment by Stefouch** [comment]
Hi @MadLetter 

Could you write me a list of missing actions ? (It's a bit of a mess in the core book to find them all)
