### ISSUE TITLE
Quicker weapon actions

### ISSUE THREAD

**Issue by tinwe** [fvtt-fria-ligan/twilight2000-foundry-vtt#103]
### Is your feature request related to a problem? Please describe.
Currently, you will have to first click the weapon in your inventory, to have a dialogue popup in the chat about the weapon, just to click the "Attack" button in that chat dialogue to open up another popup dialogue with the options for the attack, and then click attack once more, before the attack actually fires.
I would propose that the first click on the weapon opens up the second popup dialogue directly without spamming the chat first. It would both be more intuitive for all players not aquinted with the quirks of Foundry, while skipping an unecessary step and making the combat flow more quickly.

### Who would use it?
Everyone who would like a faster and more streamlined combat management.

### What part of the system?
Combat

### How would it work?
I would propose that the first click on the weapon opens up the second popup dialogue directly without spamming the chat first. 

### Why should this be added?
It would both be more intuitive for all players not aquinted with the quirks of Foundry, while skipping an unecessary step and making the combat flow more quickly.

### Additional context
I think the only reason for the weapon to popup in the chat first, would be to present the stats of the said weapon for the GM and players, but one could argue that the chat result could display the damage and crit values as well.
The player could always click edit to display all the info about the weapon any time anyhow, if one wish to.

**Comment by Stefouch** [comment]
I agree with this and I'll put this suggestion on the update wagon!
