### ISSUE TITLE
Foundry VTT v10

### ISSUE THREAD

**Issue by Akexis** [fvtt-fria-ligan/twilight2000-foundry-vtt#104]
This isn't so much an Issue and I apologize for putting this here, I couldn't figure out how to contact anyone in regard to this game and the Foundry v10 update. It looks like they've changed the data schema, so currently T2K4E is extremely buggy and I'm going to have to roll back to v9. I was wondering if there is going to be efforts made to make the module compatible with v10? There's a lot of awesome new features they've added that I would like to capitalize on and enjoy.

**Comment by Stefouch** [comment]
Hi @Akexis ! Thank you for you message! I understand your frustration, but don't worry, I should have completed the new release in a couple days. V10 did break a lot of thinks in the journal entries, and I want the coreset modules to be ready before releasing the update for the game system.

**Comment by Akexis** [comment]
This is great news! And fast! That's all I wanted to know, thank you so much.
