### ISSUE TITLE
System title offset in "Game Systems" tab of Foundry setup

### ISSUE THREAD

**Issue by urpwnd** [fvtt-fria-ligan/twilight2000-foundry-vtt#116]
### Describe the bug

" Twilight: 2000 (4th Edition)" shows at the top of the list of Game Systems, out of alphabetical order.

### Reproduction

1. log into the administrative UI
2. go to the "Game Systems" tab.
3. observe that " Twilight: 2000 (4th Edition)" is the first game system in the list, out of alphabetical order

I have uninstalled and reinstalled the system to verify that it's a bug in the current release.

### System Info

```sh
Windows 10
Chrome
version 10 build 288 (current as of 2020-10=18)
```

### Priority this issue should have?

Low (formatting issues, things that don't impact operation)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
I see why. The "extra space" is actually a "military helmet" emoji that is not rendered in your computer and/or web browser.

It should look like this:
![image](https://user-images.githubusercontent.com/47865544/196627475-0b331ec7-5931-4eeb-9f57-8b4734e2c683.png)


https://emojipedia.org/military-helmet/

And indeed, the emoji puts it at the top of the game systems list that are sorted alphabetically.

**Comment by Stefouch** [comment]
If it bothers you, until I find a fix for this issue, you can modify the game title by yourself.

Head to your Foundry User Data folder: `Data/systems/t2k4e`. There is a file named `system.json` where you can change the `title` value with a text editor (notepad, or any similar will work):
![image](https://user-images.githubusercontent.com/47865544/196628787-c1aa96c6-3469-4373-9812-96674c8a175b.png)

That empty box character you see → that's the conflicting emoji.

Be careful to not change other values and the structure of the file (those `{ : " " , }` characters must stay). *(If you did a mistake, just re-install the whole game system. It won't affect your game World.)*

Changing the title will have no impact on your Worlds. It is just cosmetic.

Note that any change on these files will be overwritten at the next game system update.

**Comment by urpwnd** [comment]
How weird that windows 10 doesn't support that emoji that came out like **_3 years ago_**. All my apple devices show it just fine.

I will say that I'm all for the emoji, but could it be after 2000 or at the end instead, so the system will still show up alphabetically?

**Comment by Stefouch** [comment]
> could it be after 2000 or at the end instead, so the system will still show up alphabetically?

This is a great suggestion!
