### ISSUE TITLE
Draw Encounter Card results are displaying for Players

### ISSUE THREAD

**Issue by SerotoninRonin** [fvtt-fria-ligan/twilight2000-foundry-vtt#123]
### Describe the bug

When the GM rolls the Draw Encounter Card macro the results are displayed for players, even if the GM has Private Rolls noted

### Reproduction

1. Login as GM
2. Set Chat to "Private GM Roll"
3. Activate the macro "Draw Encounter Card"
4. Encounter Card draws and is visible to Playesr

### System Info

```sh
OS: Windows 10
Client: Chrome
Foundry Version: 10.291
T2K4E Version: 10.1.0
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
Is it fixed now ?

**Comment by SerotoninRonin** [comment]
I am still able to see the cards as a player.

**Comment by SerotoninRonin** [comment]
Seems to be fixed AFAI can tell.
