### ISSUE TITLE
Improper modification increase of base die

### ISSUE THREAD

**Issue by EmptyOwl01** [fvtt-fria-ligan/twilight2000-foundry-vtt#124]
### Describe the bug

So I have noticed a pretty serious bug in the Foundry T2k4e ruleset. As per page 46 "If you lack a skill level and start with just a single base die, step up by adding a D6 (as one step up) and step it up further as needed." 

Currently, the ruleset increases the base attribute die to d12 before adding an extra d6 and beginning the proper balancing, as per page 45 "When stepping up and down, always try to balance your dice as much as possible – i.e. step up a lower base die first, and downstep a higher base die. You can never go above two D12s, no matter what modifiers you have. To downstep past two D6s, remove one die. You can never go below one D6."

### Reproduction

set skill to none/F, make sure attribute die isn't d12, roll skill with a +1 modifier, and instead of adding an extra d6, it will step the attribute die up one.

### System Info

```sh
windows
```

### Priority this issue should have?

Critical (bot crash, extremely major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
Bug confirmed.

Related to #45

**Comment by Stefouch** [comment]
This will be fixed in the next update.
