### ISSUE TITLE
New Initiative card system not supporting Combat Awareness

### ISSUE THREAD

**Issue by tinwe** [fvtt-fria-ligan/twilight2000-foundry-vtt#133]
### Describe the bug

Players with the Speciality "Combat Awareness - When drawing initiative, you may draw two cards instead of one and choose which one to act on." will not get the option to pick two cards when drawing intiative cards with the new card system.

### Reproduction

Create a character with the speciality "Combat Awareness". 
Enter combat mode.
"Roll initiative" for everyone.
The characters with "Combat Awareness" will get one card as everyone and there is no way for them to pick another card and select what to use.

### System Info

```sh
Several different player clients, mostly Chrome, but using the latest Foundry and T2k system.
Foundry 10, build 291
Twilight: 2000 (4th edition) system: 10.2.0
Twilight: 2000 (4th edition) core set: 2.1.0
Year Zero Engine Combat: 1.0.1
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by tinwe** [comment]
Sorry for that. I had already testet with and without Next Up without result, but when I deactivated Reverse Initiative Order, some new features appeared, since there was card icons next to the battle tracker, but I still recieve the same error message about "There are not enough cards left. Shuffling the Deck." when trying to click the hotkey macro supplied for players picking their own initiative, and when I try to roll initiative for everyone as a GM, there's no option to pick more cards for the players with the speciality.
Are both ways to generate initiative intended to be supported or what is the prefered method? Macro or GM button on combat tracker?

This is the error message in console when the player tries the hotkey macro.

foundry.js:5099 Foundry VTT | Rendering Dialog
foundry.js:59187 There are not enough cards left. Shuffling the Deck.
fetch @ foundry.js:59187
foundry.js:59187 There are no available results which can be drawn from this table.
fetch @ foundry.js:59187
VM821:80 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'data')
[No packages detected]
    at _rollInitiative (eval at _executeScript (foundry.js:20080:16), <anonymous>:80:44)
Fetch event handler is recognized as no-op. No-op fetch handler may bring overhead during navigation. Consider removing the handler if possible.

**Comment by Stefouch** [comment]
> Are both ways to generate initiative intended to be supported or what is the prefered method? Macro or GM button on combat tracker?

Button in the combat tracker. If you want your player to have a choice, you need to uncheck the option cited above, and let them click the card icon themself.

The initiative macro is something else that work differently. But now it is dead, it won't work anymore.

**Comment by Stefouch** [comment]
See screenshot:
![image](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/47865544/5bc91c9c-630a-496b-b544-4c9ccc050e41)

**Comment by tinwe** [comment]
Thanks for the clarification.
However, when the player with Combat Awareness ("Karl" in the image) clicks that icon before I roll initiative for everyone, he only gets one regular initiative card and no option to pick two and select one. He also can not repick another initiative card when initiative has been set.
![Skärmbild 2023-05-20 190034](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/4280267/1d3f9e00-3f6b-48ac-a904-957e0ba3f0e9)

The same goes if I as a GM roll initiative for everyone, "Karl" is not able to repick initiative, when initiative has been set for him.

![Skärmbild 2023-05-20 190119](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/4280267/224f0269-6654-443e-966c-b42dbd53c534)

**Comment by Stefouch** [comment]
Is this setting correct in your world (case sensitive) ?
![image](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/47865544/b58eae24-9ac3-4768-9f6a-361c77af0852)

**Comment by tinwe** [comment]
No, that field was blank by default.
I've added "system.drawSize" to that field, but the problem persists, with the player not being able to pick more initiative cards.

**Comment by Stefouch** [comment]
![image](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/47865544/8c28b595-2fbf-46ca-8fd0-cce1db6c65a4)

I am sorry I cannot reproduce your issue.

When I prepare a character with a +1 Combat Awareness modifier, and put it in combat, I get the choice between two cards when I hit the button "Draw Initiative" next to the combatant in the sidebar (the white icon with four cards).

**Comment by tinwe** [comment]
I never get that dialogue option. Neither as the GM nor the players themselves.
How should we go around to pick initiative cards correctly?
Should the players themselves click the four cards-button? Should I click it as the GM? Should I click any of the "Roll initiative for all" buttons? 
Any roll or click only results in a two digit iniative result, but no cards except those presented in chat.

![Skärmbild 2023-07-20 143343](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/4280267/ec402173-e782-48bc-b451-9dfe3bdb54b8)
![Skärmbild 2023-07-20 143255](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/4280267/0d809d33-02f8-419d-961c-3904c1f7b642)

All modules except T2k, Dice So Nice, Swedish and Year Zero Engine: Combat has been disabled.

The macro buttons to pick initiative cards doesn't seem to work no more. They always result in an error message claiming that there are no cards left in the deck;
`[foundry.js:68000:78](https://.eu.forge-vtt.com/scripts/foundry.js)
Uncaught (in promise) TypeError: results[0] is undefined
    _rollInitiative https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:80
    callback https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:130
    submit https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64942
    _onClickButton https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64870
    jQuery 9
    activateListeners https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64842
    _render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5815
    render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5742
    cardDialog https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:137
    prepareCombatant https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:104
    anonymous https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:141
    #executeScript https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:22757
    execute https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:22705
    _onClickMacro https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:78292
    jQuery 9
    activateListeners https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:78211
    _render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5815
    render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5742
    initializeUI https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8840
    setupGame https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8694
    _initializeGameView https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:9957
    _initializeView https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:9933
    initialize https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8619
    async* https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:90908
    async* https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:90884
[foundry.js line 22753 > AsyncFunction:80:3](https://xxxxx.eu.forge-vtt.com/scripts/foundry.js%20line%2022753%20%3E%20AsyncFunction)
    _rollInitiative https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:83
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    callback https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:130
    submit https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64942
    _onClickButton https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64870
    jQuery 9
    activateListeners https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:64842
    _render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5815
    AsyncFunctionNext self-hosted:852
    (Async: async)
    render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5742
    cardDialog https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:137
    prepareCombatant https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:104
    anonymous https://xxxxx.eu.forge-vtt.com/scripts/foundry.js line 22753 > AsyncFunction:141
    #executeScript https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:22757
    execute https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:22705
    _onClickMacro https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:78292
    jQuery 9
    activateListeners https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:78211
    _render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5815
    AsyncFunctionNext self-hosted:852
    (Async: async)
    render https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:5742
    initializeUI https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8840
    setupGame https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8694
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    _initializeGameView https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:9957
    _initializeView https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:9933
    initialize https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:8619
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonym> https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:90908
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonym> https://xxxxx.eu.forge-vtt.com/scripts/foundry.js:90884`

**Comment by Stefouch** [comment]
> The macro buttons to pick initiative cards doesn't seem to work no more. They always result in an error message claiming that there are no cards left in the deck;
That macro is deprecated and does not work anymore. It should be removed.

**Comment by tinwe** [comment]
So, what would you say is best practice? The intended way to pick initiative cards in v11 of the T2k module?

**Comment by tinwe** [comment]
Could it be a Forge issue when the game is hosted on Forge?

**Comment by Stefouch** [comment]
> Sorry for the macro error logs. Have had this issue opened for too long, that I forgot that you already answered that question. But what would you say is best practice? The intended way to pick initiative cards in v11 of the T2k module?

Your players or yourself have to use the Foundry way: click the draw init button (with the Year Zero Combat module)
![image](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/47865544/e8cb5be0-7481-4124-a147-2e650a5380f8)

The macro does not work anymore due to a breaking change made by Foundry in V10 or V11 (can't remember which one). I did not fix it because Year Zero Combat replaces it.

**Comment by tinwe** [comment]
We have tried clicking that icon and it produces a chat message with the initiative card drawn as well as the corresponding initiative number in the battle tracker. No dialogue for selecting multiple cards, like the macro used to question.
No error messages in console either, but these log messages;

Foundry VTT | Created 2 Card documents with ids: [O98Tv1kqxHCmWBGT,PsI8lHnu0OA3tync] in parent Cards [AmspMHbXiVlMqxhR] [commons.js:8711:20](https://xxxxxx.eu.forge-vtt.com/scripts/commons.js)
Foundry VTT | Created ChatMessage with id [ZWvI83kwhots4ESa] [commons.js:8711:20](https://xxxxxx.eu.forge-vtt.com/scripts/commons.js)
Foundry VTT | Unloading audio element - modules/yze-combat/assets/sounds/card-flip.wav [foundry.js:91850:13](https://xxxxxx.eu.forge-vtt.com/scripts/foundry.js)

I've disabled all other modules except All modules except Forge, T2k, Dice So Nice, Swedish and Year Zero Engine: Combat.
Is this a Forge or Swedish issue then or what is causing it?

**Comment by Stefouch** [comment]
> Is this a Forge or Swedish issue then or what is causing it?

I don't think so. No error is thrown.

From the log you shared, two init cards are drawn.
But you only see one.

Can you send a screenshot of your `Year Zero Engine: Combat` settings ?
