### ISSUE TITLE
Pushing roll reduces ammo

### ISSUE THREAD

**Issue by Vcutter** [fvtt-fria-ligan/twilight2000-foundry-vtt#134]
### Describe the bug

When pushing a firearms roll using no additional ammo dice, the system depletes the magazine by one additional ammo.
Meaning you lose one ammo in the initial action and another when pressing the push. 

### Reproduction

Click Firearm.
Select no additional RoF.
Roll.
Select "push"

### System Info

```sh
Windows 10
Tested on Foundry (10.291) desktop app and Forge hosted version (Chrome).
Twilight Core 2.1.0
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
Thank you for your bug report!
I've found the source of the issue. A patch of the game system will be released very soon (later today or tomorrow).
