### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Bakali77** [fvtt-fria-ligan/twilight2000-foundry-vtt#140]
### Description

Hello, I have made a fan translation for the game to have it in Spanish, and I would like to share it with you in case you want to include it in future updates.

[Traduccion Foundry TW2K.zip](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/files/12284548/Traduccion.Foundry.TW2K.zip)

### Suggested solution

I send you the translation in an attached file.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Bakali77** [comment]
There is a typo in the above file. This is corrected, sorry for the inconvenience.
[Traduccion Foundry TW2K.zip](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/files/12284629/Traduccion.Foundry.TW2K.zip)

**Comment by Stefouch** [comment]
Hi @Bakali77,

Thank you for your help! I will add the translation asap.

In the future, you can use this website to translate the game system: https://weblate.foundryvtt-hub.com/projects/t2k4e/main/

**Comment by Stefouch** [comment]
PS: reminder to me:
- [ ] Add the above hyperlink to the project's readme.
