### ISSUE TITLE
Spanish translation 1.1

### ISSUE THREAD

**Issue by Bakali77** [fvtt-fria-ligan/twilight2000-foundry-vtt#143]
### Description

Sorry, I found a typo in a word. I have translated it correctly and I am sending you the modified attached file.

### Suggested solution

I am sending you the modified attached file.
[Traduccion Foundry TW2K_1.1.zip](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/files/12328162/Traduccion.Foundry.TW2K_1.1.zip)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
Please use the Weblate for any change of a translation: https://weblate.foundryvtt-hub.com/projects/t2k4e/main/es/
