### ISSUE TITLE
Head Hits count as a Success In 12.0.1

### ISSUE THREAD

**Issue by rdefendi** [fvtt-fria-ligan/twilight2000-foundry-vtt#152]
### Describe the bug

After upgrading to system version 12.0.1, T2K counts the location die as a skill die for the purposes of counting hits. In other words, if you get a head hit, it counts as a success. If you miss your attack, but still roll a head hit, it counts as a hit with one success (making it impossible to miss the head.)

Here is a screenshot of the issue in v11 build 315.

![Screenshot 2024-06-24 093819](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/11877369/5d38c6e6-07c9-43fb-9fc1-e8923be9c6ec)

Here is a sceenshot of the issue in v12 build 327.

![Screenshot 2024-06-24 094748](https://github.com/fvtt-fria-ligan/twilight2000-foundry-vtt/assets/11877369/07d51fa3-af12-4f01-9913-3d4d4099a926)

Both tests were done with modules turned off and 12.0.1.

Reverting the v11 to 11.0.1 fixes the issue, but obviously we need to fix it for v12.

### Reproduction

Attack with a weapon until you get a head result on the location die.

### System Info

```sh
v11 build 315, v12 build 327, system 12.0.1.
```

### Priority this issue should have?

Medium (minor functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
I see that both version 11.0.1 (Foundry V11) and 12.0.0 (Foundry V12) has this issue. Correct?
