### ISSUE TITLE
Rolling a modified roll with ammo dice not working

### ISSUE THREAD

**Issue by Stefouch** [fvtt-fria-ligan/twilight2000-foundry-vtt#156]
### Describe the bug

In certain situation, rolling dice from the roll dialog fails. Nothing is rolled and an error is thrown in the log.

Looks like it is when you modify a roll that has ammo dice.

### Reproduction

I tried different rolls and two situations occur:

First case:
1. Open the Swedish Soldier token (or any other I believe)
2. In the inventory, click the Ak 5 weapon
3. In the roll dialog, change "Modifier" to +1 (or -1) and click roll.
4. Nothing is rolled

Second case:
1. Run the "Roll Dice" macro
2. Change "Rate of Fire" to 1 or more
3. Change "Modifier" to something else, like +1 or -1

### System Info

```sh
OS: Win 10 22H2
Client: Brave 1.67.123 - chromium 126.0.6478.126
Foundry: V12.328
System: 12.0.2
```

### Logs

```js
Error: The async option for Roll#evaluate has been removed. Use Roll#evaluateSync for synchronous roll evaluation.
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at YearZeroRoll.evaluate (foundry-esm.js:63360:23)
    at YearZeroRoll.roll (foundry-esm.js:63541:19)
    at T2KRoller.taskCheck (dice.js:136:16)

foundry-esm.js:63433 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'class')
    at YearZeroRoll._evaluateASTAsync (foundry-esm.js:63433:17)
    at YearZeroRoll._evaluateASTAsync (foundry-esm.js:63442:35)
    at YearZeroRoll._evaluateASTAsync (foundry-esm.js:63442:35)
    at YearZeroRoll._evaluate (foundry-esm.js:63414:32)
    at async T2KRoller.taskCheck (dice.js:136:5)
```

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
In V10, no problem

**Comment by Stefouch** [comment]
Happens also with the Location Die

**Comment by DrOgres** [comment]
I submitted a PR to YZUR that will fix this.  as soon as that is updated I will get T2K updated as well

**Comment by Kirche00** [comment]
I am experiencing the same issue

**Comment by Mrafala** [comment]
I am also experiencing this problem.

**Comment by DrOgres** [comment]
> I am also experiencing this problem. Is there an ETA on the fix?

just waiting on the fix to percolate through the tech stack should be soon(tm)

**Comment by Mrafala** [comment]
> > I am also experiencing this problem. Is there an ETA on the fix?
> 
> just waiting on the fix to percolate through the tech stack should be soon(tm)

Thanks!! Crossing my fingers it's before my next session (a week from today).

**Comment by Stefouch** [comment]
For reference: https://github.com/Stefouch/foundry-year-zero-roller/pull/14

**Comment by Kirche00** [comment]
Awesome thanks 👍

**Comment by Mrafala** [comment]
Much appreciated!
