### ISSUE TITLE
Reordering of gear items

### ISSUE THREAD

**Issue by doct** [fvtt-fria-ligan/twilight2000-foundry-vtt#18]
### Is your feature request related to a problem? Please describe.
No problem, just usability. It would be nice to be able to re-order gear items in the equipment tab, as in other systems.

### Who would use it?
Everyone who want to have their char sheet in order. :-)

### What part of the bot?
PC char sheet, gear tab.

### How would it work?
You'd drag and drop a gear item on top of another gear item. The dropped item gets sorted before the item dropped upon. Works in other systems that way.

### Why should this be added?
People like to have control over their char sheet, as is in real life, too.

**Comment by Stefouch** [comment]
Hi @doct ,

This is a great suggestion and I'll add it the to-do list.
I'll take a bit of work to create such sorting feature, so I'll look into it after the release of the premium modules (which I'm also writing for Free League).

**Comment by doct** [comment]
Great to hear, that official modules are coming, and that you are writing it! Can any ETA be communicated? I am a bit hesitant at the moment to create Foundry content from the PDFs in my world, as I don't want the work involved to be wasted when the official content modules are released. However, I don't want to wait for virtual eternity to actually play T2KE4.

**Comment by Stefouch** [comment]
As a GM too, I completely understand your point, but unfortunately it is not my responsibility to communicate an ETA for the premium modules. You have to contact Free League's support at `support@frialigan.se`, and they may or may not be more precise that "soon".

**Comment by Stefouch** [comment]
This feature has been added with the last update.
