### ISSUE TITLE
Food and Water Tracking Tick Marks 

### ISSUE THREAD

**Issue by lystraeudaimon** [fvtt-fria-ligan/twilight2000-foundry-vtt#50]
### Is your feature request related to a problem? Please describe.

Food and Water tracking has me adding and deleting the same inventory items over and over again. 
### Who would use it?

GM and players
### What part of the system?

Inventory
### How would it work?

Add check boxes like used for health and stress for Water, Field Rations, Domestic Food, Wild Food make the total number of boxes for each editable like the health and stress tracker. Players or GM can check off/check on water and food when it's eaten or found. 
### Why should this be added?

It would simplify an important part of a a survival game, making it easier for DM's and players to track food/water usage

**Comment by Stefouch** [comment]
Would it ease the players' life if the quantity was editable directly on the inventory sheet instead of having to click the edit button each time ?

**Comment by tinwe** [comment]
Yes this would help the quality of life a lot for the book keeping.
