### ISSUE TITLE
Cards ?

### ISSUE THREAD

**Issue by Stefouch** [fvtt-fria-ligan/twilight2000-foundry-vtt#77]
Now that Foundry V9 brought support for cards, it would be nice to implement initiative cards (and encounter cards) for Twilight 2000.

Todo list:
- [ ] Learn the new Foundry cards API.
- [ ] Create a card system for T2K4E.
  - [ ] Make it work with initiative drawing.
- [ ] Encode all the cards.
- [ ] Test and PR.

**Comment by tinwe** [comment]
Sounds awesome. Can't wait for this to be implemented!

**Comment by Stefouch** [comment]
Nobody is working on it yet. So your help is more then welcome!

Le lun. 2 mai 2022 à 16:19, Jahmal Brown ***@***.***> a
écrit :

**Comment by MadJay** [comment]
Awesome, I made a fork and will dive in.

**Comment by tinwe** [comment]
> Awesome, I made a fork and will dive in.

Would surely be helpful if some of the requests from this thread could be implemented along with the card support
https://github.com/Stefouch/t2k4e/issues/100#issuecomment-1134457416

**Comment by Stefouch** [comment]
Initiative cards are now supported with the new "Year Zero: Combat" module.
